name: Tests
on:
  push:
    branches:
      - stacklet/integration
  pull_request:
    branches:
      - stacklet/integration
permissions:
  contents: read
jobs:
  backend-unit-tests:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Install Dependencies
        uses: ./.github/composites/install
        with:
          install-yarn-deps: 'false'
      - name: Run Backend Tests
        run: just backend-test

  # frontend-unit-tests:
  #   runs-on: ubuntu-22.04
  #   permissions:
  #     id-token: write
  #     contents: read
  #   steps:
  #     - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
  #       with:
  #         persist-credentials: false
  #     - name: Install Dependencies
  #       uses: ./.github/composites/install
  #       with:
  #         aws-role: arn:aws:iam::653993915282:role/ci-github-actions
  #     - name: Run Frontend Tests
  #       run: just frontend-test
