name: Tests
on:
  push:
    branches:
      - stacklet/integration
  pull_request:
    branches:
      - stacklet/integration
permissions:
  contents: read
jobs:
  backend-lint:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Install Dependencies
        uses: ./.github/composites/install
        with:
          install-yarn-deps: 'false'
      - name: Install and configure Poetry
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
        with:
          version: ${{ env.POETRY_TOOL_VERSION }}
          virtualenvs-in-project: true
      - name: Set up Python ${{ env.PYTHON_TOOL_VERSION }}
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: ${{ env.PYTHON_TOOL_VERSION }}
          cache: poetry
      - name: Cache Poetry dependencies
        id: cache
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: .venv
          key: setup-python-${{ runner.os }}-python-${{ env.PYTHON_TOOL_VERSION }}-poetry-v2-${{ hashFiles('**/poetry.lock') }}
      - run: just backend-install
      - run: just backend-lint

  backend-unit-tests:
    runs-on: ubuntu-22.04
    needs: backend-lint
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Install Dependencies
        uses: ./.github/composites/install
        with:
          install-yarn-deps: 'false'
      - name: Run Backend Tests
        run: just backend-test

  frontend-lint:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Install Dependencies
        uses: ./.github/composites/install
        with:
          aws-role: arn:aws:iam::653993915282:role/ci-github-actions
      - name: Run Frontend Lint
        run: just frontend-lint

  frontend-unit-tests:
    runs-on: ubuntu-22.04
    needs: frontend-lint
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Install Dependencies
        uses: ./.github/composites/install
        with:
          aws-role: arn:aws:iam::653993915282:role/ci-github-actions
      - name: Run Frontend Tests
        run: just frontend-test

  frontend-e2e-tests:
    runs-on: ubuntu-22.04
    needs: frontend-lint
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Install Dependencies
        uses: ./.github/composites/install
        with:
          aws-role: arn:aws:iam::653993915282:role/ci-github-actions
      - name: Run Frontend E2E Tests
        run: just frontend-e2e-test
